export const myProductList = [
  {
    id: 1,
    imgUrl: "/asset/keyboard.jpeg",
    productName: "Apple 정품 매직 키보드",
    productPrice: "109,480",
    productPlatform: "/asset/coupang.png",
    purchaseDate: "2023.08.18",
    platform: "쿠팡",
    url: "https://www.coupang.com/vp/products/6011323838?vendorItemId=78186257993&sourceType=MyCoupang_my_orders_list_product_title&isAddedCart=",
  },
  {
    id: 2,
    imgUrl: "/asset/airPod.jpeg",
    productName: "Apple 2022 에어팟 프로 2세대 블루투스 이어폰",
    productPrice: "316,780",
    productPlatform: "/asset/11street.jpeg",
    purchaseDate: "2023.07.02",
    platform: "11번가",
    url: "https://www.11st.co.kr/products/4951964779?gclid=Cj0KCQjw_5unBhCMARIsACZyzS0LEgjG9tonDP0J0x7BF5ajf_LQuVE3mPDD4YMU2T0yAoLOEP4HQGUaAqSbEALw_wcB&utm_term=&utm_campaign=googleshopping_pc_basic_new&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6",
  },
  {
    id: 3,
    imgUrl: "/asset/drG.jpeg",
    productName: "닥터지 블랙 스네일크림",
    productPrice: "9,450",
    productPlatform: "/asset/11street.jpeg",
    purchaseDate: "2023.05.19",
    platform: "11번가",
    url: "https://www.11st.co.kr/products/5339520566?gclid=Cj0KCQjw_5unBhCMARIsACZyzS3dycnxm8hgMyP6LB1JpMzUkMXeDWmynVD3_tX8k_EOt6lA7_pBHA0aAoDGEALw_wcB&utm_term=&utm_campaign=googleshopping_pc_basic_new&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6",
  },
  {
    id: 4,
    imgUrl: "/asset/appleWatch.jpeg",
    productName:
      "Apple 애플워치 Ultra 오션 밴드 49mm GPS+Cellular 티타늄 케이스",
    productPrice: "1,149,000",
    productPlatform: "/asset/coupang.png",
    purchaseDate: "2023.03.19",
    platform: "쿠팡",
    url: "https://www.coupang.com/vp/products/6790570818?vendorItemId=83202424969&sourceType=MyCoupang_my_orders_list_product_title&isAddedCart=",
  },
];

export const myProductListAfterGmarketLogin = [
  {
    id: 1,
    imgUrl: "/asset/keyboard.jpeg",
    productName: "Apple 정품 매직 키보드",
    productPrice: "109,480",
    productPlatform: "/asset/coupang.png",
    purchaseDate: "2023.08.18",
    platform: "쿠팡",
    url: "https://www.coupang.com/vp/products/6011323838?vendorItemId=78186257993&sourceType=MyCoupang_my_orders_list_product_title&isAddedCart=",
  },
  {
    id: 2,
    imgUrl: "/asset/airPod.jpeg",
    productName: "Apple 2022 에어팟 프로 2세대 블루투스 이어폰",
    productPrice: "316,780",
    productPlatform: "/asset/11street.jpeg",
    purchaseDate: "2023.07.02",
    platform: "11번가",
    url: "https://www.11st.co.kr/products/4951964779?gclid=Cj0KCQjw_5unBhCMARIsACZyzS0LEgjG9tonDP0J0x7BF5ajf_LQuVE3mPDD4YMU2T0yAoLOEP4HQGUaAqSbEALw_wcB&utm_term=&utm_campaign=googleshopping_pc_basic_new&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6",
  },
  {
    id: 3,
    imgUrl: "/asset/drG.jpeg",
    productName: "닥터지 블랙 스네일크림",
    productPrice: "9,450",
    productPlatform: "/asset/11street.jpeg",
    purchaseDate: "2023.05.19",
    platform: "11번가",
    url: "https://www.11st.co.kr/products/5339520566?gclid=Cj0KCQjw_5unBhCMARIsACZyzS3dycnxm8hgMyP6LB1JpMzUkMXeDWmynVD3_tX8k_EOt6lA7_pBHA0aAoDGEALw_wcB&utm_term=&utm_campaign=googleshopping_pc_basic_new&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6",
  },
  {
    id: 4,
    imgUrl: "/asset/wax.jpeg",
    productName: "슈돌츠 매트 프리즈 헤어왁스 80g",
    productPrice: "8,900",
    productPlatform: "/asset/gmarket_logo.png",
    purchaseDate: "2023.05.14",
    platform: "지마켓",
    url: "https://www.11st.co.kr/products/1667817571?gclid=Cj0KCQjw_5unBhCMARIsACZyzS1xb3txZ8JiGbVNZy8cVj_hlR7JHeKSRarvE7nOYifHpqMaEK0TsoEaAh6EEALw_wcB&utm_term=&utm_campaign=%B0%CB%BB%F6%26gt%3B%B1%B8%B1%DB%BC%EE%C7%CE%26gt%3B%BA%A3%BD%BA%C6%AE&utm_source=%B1%B8%B1%DB_PC_S_%BC%EE%C7%CE&utm_medium=%B0%CB%BB%F6",
  },
  {
    id: 5,
    imgUrl: "/asset/hair.png",
    productName: "미쟝센 스무스 앤 실키 모이스처 데일리 트리트먼트",
    productPrice: "49,000",
    productPlatform: "/asset/gmarket_logo.png",
    purchaseDate: "2023.05.08",
    platform: "지마켓",
    url: "http://global.gmarket.co.kr/item?goodscode=2030823447",
  },
  {
    id: 6,
    imgUrl: "/asset/appleWatch.jpeg",
    productName:
      "Apple 애플워치 Ultra 오션 밴드 49mm GPS+Cellular 티타늄 케이스",
    productPrice: "1,149,000",
    productPlatform: "/asset/coupang.png",
    purchaseDate: "2023.03.19",
    platform: "쿠팡",
    url: "https://www.coupang.com/vp/products/6790570818?vendorItemId=83202424969&sourceType=MyCoupang_my_orders_list_product_title&isAddedCart=",
  },
];
